print('what do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do scientists call an astronout\'s cavity?')
input()
print('a black hole')
print()
print('knock knock.')
input()
print('Who\'s there?')
input()
print('Amos')
input()
print('Amos who?')
input()
print('A mosquito')
